---
title: "Green Sea Turtle Injuries"
author: "Nick Castro & Justin Mann"
date: "2023-12-14"
output: html_document
---

```{r libraries, include=FALSE}
library(ggplot2)
library(tidyverse); theme_set(theme_classic())
```



```{r data}
#import data file
df <- read.csv("GreenSeaTurtlesInjuryData_2019-2023.csv", h=TRUE)

#filter out duplicates 
df <- df %>% distinct(ID, .keep_all = TRUE)

#what data class is injury nature (df$Nature)
class(df$Nature)

#make it a factor
df$Nature <- as.factor(df$Nature)

#use levels() to verify it's now a factor with 4 levels
levels(df$Nature)
```

```{r colorblind accessible pallet}
colorBlindPal  <- c("#000000", "#E69F00", "#56B4E9", "#009E73", 
                       "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
```

```{r plotting}
InjuryNature.plot <- ggplot(data = df, aes(Nature))+
  geom_bar(fill = "#0072B2")
InjuryNature.plot
```

```{r prop test}
#Number of Natural injuries
nat <- length(df$Nature[df$Nature=="Natural"])
anthro <- length(df$Nature[df$Nature=="Anthropogenic"])

?prop.test
anthro
nat+anthro
prop.test(anthro, nat+anthro, alternative = "two.sided", conf.level = 0.95)
```

```{r}
InjuryNature.plot <- ggplot(data = df, aes(Nature))+
  geom_bar(fill = "#E69F00")
InjuryNature.plot

```
```{r}
BodyPart
```

```{r}
BodyPart.plot <- ggplot(data = df, aes(BodyPart))+
  geom_bar(fill = "#E69F00")
BodyPart.plot
```


```

```

