---
title: "Green Sea Turtle Injuries"
author: "Justin Mann"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
---

```{r libraries}
library(tidyverse); theme_set(theme_classic())
library(rstatix)
```

```{r data}
df <- read.csv("GreenSeaTurtleInjuries_3.29.24.csv", h=TRUE)
```

```{r define factors}
df$Nature <- as.factor(df$Nature)
levels(df$Nature)

df$BodyPart <- as.factor(df$BodyPart)
levels(df$BodyPart)

df$InjuryType <- as.factor(df$InjuryType)
levels(df$InjuryType)

df$InjuryStage <- as.factor(df$InjuryStage)
levels(df$InjuryStage)

df$Source <- as.factor(df$Source)
levels(df$Source)
```

```{r CCL summary stats}
#average CCL 
meanCCL <- mean(df$CCLmax, na.rm = TRUE)
meanCCL #104.5 

sdCCL <- sd(df$CCLmax, na.rm = TRUE)
sdCCL #7.9
```


```{r Nature.plot}
Nature.plot <- ggplot(data=subset(df, !is.na(Nature) & Nature != 4), aes(x=Nature))+
  geom_bar(fill = "red")+
  labs(x = "Nature of injury", 
       y = "Count")+
  scale_x_discrete(labels = c("1" = "Anthropogenic",
                              "2" = "Natural",
                              "3" = "Unknown"))+
  theme(axis.text.x = element_text(size = 12),
          axis.title.x = element_text(size = 14),
          axis.text.y = element_text(size = 12),
          axis.title.y = element_text(size = 14),
          plot.margin = margin(15,15,15,15))
Nature.plot
```

```{r Nature of injury categories}
#Number of anthropogenic injuries
anthro <- length(df$Nature[df$Nature==1])

#Number of natural injuries
natural <- length(df$Nature[df$Nature==2])

#Number of unknown injuries
unknown <- length(df$Nature[df$Nature==3])
```

```{r injury nature comparison}
anthro_nat.ctable <- rbind(c(12,23), c(23,12))
#chisq.test(anthro_nat.ctable, correct = FALSE)
fisher.test(anthro_nat.ctable)
```
```{r post hoc source}
xtab <- as.table(rbind(
  c(26, 25, 21, 34, 34),
  c(9, 10, 14, 1, 1)
))
dimnames(xtab) <- list(
  Injured = c("No", "Yes"),
  Source = c("shark", "boat", "behavioral", "hook", "entangle")
  )

pairwise_fisher_test(xtab)
```

```{r Source.plot}
Source.plot <- ggplot(data=subset(df, !is.na(Source) & df$Source != "MS"), aes(x=Source))+
  geom_bar(fill = "red")+
  labs(x = "Injury source", 
       y = "Count")+
  theme(axis.text.x = element_text(size = 12),
          axis.title.x = element_text(size = 14),
          axis.text.y = element_text(size = 12),
          axis.title.y = element_text(size = 14),
          plot.margin = margin(15,15,15,15))
Source.plot
```


